version: '3'

services:
  mongodb:
    image: mongo
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  wait:
    image: waisbrot/wait
    links:
      - mongodb
    environment:
      - TARGETS=mongodb:27017
    depends_on:
      - mongodb
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - "8000:8081"
    depends_on:
      - wait
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
